version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: FullTextSearchDB
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fts
    ports:
      - '55434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
